name = "SparseTimeSeries"
uuid = "e40787dc-7381-49a9-a10c-5aed17658239"
authors = ["Jon Alm Eriksen <jon.alm.eriksen@protonmail.com>"]
version = "0.1.8"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
julia = "1"
JSON3 = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
